
# Load from the env file
env_files = [{ path = ".env" }]

# ---- Building docker tags ----
#
# Build the local docker file
[tasks.build-docker]
condition = { env_set = ["DOCKER_IMAGE_TAG", "GITHUB_RELEASE_VERSION"] }
command = "docker"
args = [
    "build",
    ".",
    "-t",
    "${DOCKER_IMAGE_TAG}",
    "--build-arg",
    "GITHUB_RELEASE_VERSION=${GITHUB_RELEASE_VERSION}",
]

# Build the local docker file using the version from Cargo.toml
[tasks.build-docker-version]
env = { "DOCKER_IMAGE_TAG" = "${DOCKER_IMAGE_NAME}:${CARGO_MAKE_CRATE_VERSION}" }
run_task = [{ name = "build-docker" }]

# Build the local docker file using the "latest" version tag
[tasks.build-docker-latest]
env = { "DOCKER_IMAGE_TAG" = "${DOCKER_IMAGE_NAME}:latest" }
run_task = [{ name = "build-docker" }]

# Build the local docker file using the "latest" version tag
[tasks.build-docker-all]
run_task = [
    { name = [
        "build-docker-version",
        "build-docker-latest",
    ], parallel = true },
]

# ---- Pushing docker tags ----

# Publishes the docker image using the DOCKER_IMAGE_TAG tag
[tasks.publish-docker]
condition = { env_set = [
    "DOCKER_IMAGE_TAG",
], fail_message = "Missing DOCKER_IMAGE_TAG" }
command = "docker"
args = ["push", "${DOCKER_IMAGE_TAG}"]
dependencies = ["build-docker"]

# Publish the docker image using a tag created from the verson in Cargo.toml
[tasks.publish-docker-version]
condition = { env_set = [
    "DOCKER_IMAGE_NAME",
], fail_message = "Missing DOCKER_IMAGE_NAME" }
env = { "DOCKER_IMAGE_TAG" = "${DOCKER_IMAGE_NAME}:${CARGO_MAKE_CRATE_VERSION}" }
run_task = [{ name = "publish-docker" }]

# Published the docker image under the "latest" tag
[tasks.publish-docker-latest]
condition = { env_set = [
    "DOCKER_IMAGE_NAME",
], fail_message = "Missing DOCKER_IMAGE_NAME" }
env = { "DOCKER_IMAGE_TAG" = "${DOCKER_IMAGE_NAME}:latest" }
run_task = [{ name = "publish-docker" }]

# Publishes all docker images
[tasks.publish-docker-all]
run_task = [
    { name = [
        "publish-docker-version",
        "publish-docker-latest",
    ], parallel = true },
]

[config]
default_to_workspace = false
